caddy:
  image: abiosoft/caddy:php
  container_name: caddy
  volumes:
    - /etc/caddy/certs:/root/.caddy
    - /var/www:/srv
    - /etc/caddy:/etc
  restart: unless-stopped
  ports:
    - 80:80
    - 443:443
    - 2015:2015
