services:
  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - /etc/caddy/certs:/data
      - /var/www:/srv
      - /etc/caddy:/etc/caddy
    environment:
      - ACME_AGREE=${ACME_AGREE}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    networks:
      - caddy_network

networks:
  caddy_network:
    driver: bridge
