services:
  nginx:
    image: 'bitnami/nginx'
    container_name: lempstack_nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./logs/access.log:/opt/bitnami/nginx/logs/myapp-access.log
      - ./logs/error.log:/opt/bitnami/nginx/logs/myapp-error.log
      - ./nginx/app.conf:/bitnami/nginx/conf/vhosts/app.conf
      - ./public:/myapps
    depends_on:
      - phpfpm
    networks:
      - lempstack_network
    restart: unless-stopped

  phpfpm:
    image: 'bitnami/php-fpm'
    container_name: lempstack_phpfpm
    ports:
      - '9000:9000'
    volumes:
      - ./public:/myapps
    networks:
      - lempstack_network
    restart: unless-stopped

  mysql:
    image: 'mariadb'
    container_name: lempstack_mysql
    ports:
      - '3306:3306'
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - lempstack_network
    restart: unless-stopped

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: lempstack_phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - lempstack_network

networks:
  lempstack_network:
    driver: bridge
